//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public books()
        {
            this.bookToOrder = new HashSet<bookToOrder>();
        }
    
        public int IDbook { get; set; }
        public string name { get; set; }
        public Nullable<int> IDgenre { get; set; }
        public string author { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<int> countInShop { get; set; }
        public Nullable<int> countInStock { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual genres genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookToOrder> bookToOrder { get; set; }
    }
}
